### ISSUE TITLE
Typus 4.0.0.beta1 not load I18n locale Japanese

### ISSUE THREAD

**Issue by andyduong1920** [baban/typus_lang#1]
Hi, I try add I18n Japanese for Typus, I follow with you guide
- Step 1: Create file `config/locales/typus.ja.models.yml`
- Step 2: Create file `config/locales/typus.ja.yml`
- Step 3: Create file `lib/typus_extention.rb`
- Step 4: Create file `config/initializers/development.rb` and `require "typus_extention"`

After that, I start server with `rails s` but it not work, Japanese don't show, this is my environment:
- Ruby: `2.2.2`
- Rails: `4.2.4`
- Typus: `4.0.0.beta1`
- Ubuntu: `14.04`

Please help me.

Thank you very much.

**Comment by baban** [comment]
You are latest enviroment.
I guess that caused by `Typus.avaliable_locales` method cannot override.
please type`bundle exec rails console` and `Typus.available_locales`
If printed in console `{"English"=>"en"}`, you should fix to `{"English"=>"en", "日本語" =>"ja"}`

**Comment by andyduong1920** [comment]
Hey @baban 

When I run `rails c` and `Typus.available_locales`

It return `{"English"=>"en", "日本語"=>"ja"}`

**Comment by baban** [comment]
Oh, propably source code is correct.

You move to below address. and choise you, and change your locale to "日本語".
http://localhost:3000/admin/admin_users

**Comment by andyduong1920** [comment]
Oh, I see. Typus set locale for each Account, not set locale with locale environment rails :+1: 
Thank you. :100:

**Comment by baban** [comment]
I see.😊
I feel good that solve your problem.

**Comment by andyduong1920** [comment]
:+1:
